### PR TITLE
Flush stored notifications when calling push.register()

### LINKED ISSUE #1: Callback doesn't work if the application was started by notification.
Android.
1. Fully close an app
2. Send a push
3. tap to push

### PR DESCRIPTION
**Pull request by britzl**
Fixes #1

### CODE REVIEW

File: extension-push/src/java/com/defold/push/Push.java [hunk 1]
```diff
@@ -177,6 +179,7 @@ public void run() {
                     startFirebase(activity);
                     loadSavedLocalMessages(activity);
                     loadSavedMessages(activity);
+                    flushStoredNotifications();
```
Comment (britzl) [inline extension-push/src/java/com/defold/push/Push.java:182]: The problem is that if a game calls `push.register()` and  `push.set_listener(cb)` at the same time (which is very likely) then `push.register()` will finish after `push.set_listener()`.

This is a problem since any saved notifications haven't been loaded and the listener will not trigger. Doing a flush of saved notifications immediately after push.register() will solve this problem.

File: extension-push/src/java/com/defold/push/Push.java [hunk 2]
```diff
@@ -157,16 +157,18 @@ public void stop() {
     }
 
     public void flushStoredNotifications() {
-        for (int i = 0; i < storedNotifications.size(); i++) {
-            StoredNotification n = storedNotifications.get(i);
-            if (n.wasLocal) {
-                this.listener.onLocalMessage(n.json, n.id, n.wasActivated);
-            } else {
-                this.listener.onMessage(n.json, n.wasActivated);
+        if (this.listener != null) {
```
Comment (JCash) [inline extension-push/src/java/com/defold/push/Push.java:160]: Tiny nitpick for the future.
We prefer early-outs, since I think they are easier to read and reason about.

E.g. 
```
if ( ! thing ) return;

stuff
```

File: extension-push/src/java/com/defold/push/Push.java (hunk 1 above)
Comment (JCash) [reply extension-push/src/java/com/defold/push/Push.java:182]: Not sure if anyone will ever (re)move this line, but that sound like a good code comment to me :)

**Review by JCash — APPROVED** [review]
