### PR TITLE
Set pending intent mutability

### LINKED ISSUE #46: Exception on Android 12 when cancelling notification
One of our testers upgraded from Android 11 to Android 12 on a Samsung Galaxy A03s, and is now seeing this:

```
2022-08-31 10:51:07.010 26853-26922/com.drihq.petsproto A/drihq.petsprot: java_vm_ext.cc:579] JNI DETECTED ERROR IN APPLICATION: JNI GetObjectClass called with pending exception java.lang.IllegalArgumentException: com.drihq.petsproto: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    java_vm_ext.cc:579] Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
    java_vm_ext.cc:579]   at void android.app.PendingIntent.checkFlags(int, java.lang.String) (PendingIntent.java:382)
    java_vm_ext.cc:579]   at android.app.PendingIntent android.app.PendingIntent.getBroadcastAsUser(android.content.Context, int, android.content.Intent, int, android.os.UserHandle) (PendingIntent.java:673)
    java_vm_ext.cc:579]   at android.app.PendingIntent android.app.PendingIntent.getBroadcast(android.content.Context, int, android.content.Intent, int) (PendingIntent.java:660)
    java_vm_ext.cc:579]   at void com.defold.push.Push.cancelNotification(android.app.Activity, int, java.lang.String, java.lang.String, java.lang.String, int) (Push.java:382)
    java_vm_ext.cc:579] 
    java_vm_ext.cc:579]     in call to GetObjectClass
2022-08-31 10:51:07.277 26853-26922/com.drihq.petsproto A/drihq.petsprot: runtime.cc:669] Pending exception java.lang.IllegalArgumentException: com.drihq.petsproto: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    runtime.cc:669] Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
    runtime.cc:669]   at void android.app.PendingIntent.checkFlags(int, java.lang.String) (PendingIntent.java:382)
    runtime.cc:669]   at android.app.PendingIntent android.app.PendingIntent.getBroadcastAsUser(android.content.Context, int, android.content.Intent, int, android.os.UserHandle) (PendingIntent.java:673)
    runtime.cc:669]   at android.app.PendingIntent android.app.PendingIntent.getBroadcast(android.content.Context, int, android.content.Intent, int) (PendingIntent.java:660)
    runtime.cc:669]   at void com.defold.push.Push.cancelNotification(android.app.Activity, int, java.lang.String, java.lang.String, java.lang.String, int) (Push.java:382)
    runtime.cc:669] 
```

### PR DESCRIPTION
**Pull request by britzl**
Fixes #46

### CODE REVIEW

File: extension-push/src/java/com/defold/push/Push.java [hunk 1]
```diff
@@ -351,10 +360,11 @@ public void scheduleNotification(final Activity activity, int uid, long timestam
         intent.setAction("uid" + uid);
         intent.putExtra(packageName + DEFOLD_NOTIFICATION, getLocalNotification(appContext, extras, uid));
 
-
-        PendingIntent pendingIntent = PendingIntent.getBroadcast(appContext, 0, intent, PendingIntent.FLAG_ONE_SHOT);
+        final int flags = createPendingIntentFlags(PendingIntent.FLAG_ONE_SHOT);
+        PendingIntent pendingIntent = PendingIntent.getBroadcast(appContext, 0, intent, flags);
         try {
-            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
+            // from S the use of exact alarms requires additional permissions
```
Comment (britzl) [inline extension-push/src/java/com/defold/push/Push.java:366]: I don't think we want to add another permission?

https://developer.android.com/training/scheduling/alarms#exact-permission-declare

**Review by AGulev — APPROVED** [review]

File: extension-push/src/java/com/defold/push/Push.java (hunk 1 above)
Comment (AGulev) [reply extension-push/src/java/com/defold/push/Push.java:366]: it seems like it's not necessary.
We can make it optional using flag in game.project and Mustache template in AndroidManifest for that.
